// 职业新闻数据库（每个职业 10 条新闻，所有链接均经 2026-06-02 验证可访问）

const careerNewsDatabase = {
    'Information Technology': [
        { title: '💻 Nvidia desafia Apple e Intel ao anunciar chip de IA para computadores pessoais', description: 'Nvidia announces RTX Spark "superchip" for personal computers, challenging Apple and Intel in the AI PC market.', source: { name: 'BBC News' }, url: 'https://www.bbc.com/portuguese/articles/c4g413yrly2o', publishedAt: '2026-06-01T00:00:00.000Z' },
        { title: '🤖 AI chatbots can be misled by fake online content', description: 'BBC investigation finds ChatGPT, Gemini, and Google AI search repeated false claims, prompting policy changes.', source: { name: 'Dainik Bhaskar' }, url: 'https://www.bhaskarenglish.in/tech-science/news/chatgpt-gemini-google-ai-search-false-claims-policy-changes-138080887.html', publishedAt: '2026-06-01T00:00:00.000Z' },
        { title: '🔐 Google Willow quantum computing chips reach UK scientists', description: 'King’s College London becomes first academic group in UK to gain access to Google’s advanced quantum computer chip.', source: { name: 'Times of India' }, url: 'https://timesofindia.indiatimes.com/home/education/news/scientists-from-this-college-become-the-first-in-uk-to-get-google-willow-quantum-computing-chips-why-it-matters/articleshow/120928262.cms', publishedAt: '2026-05-30T00:00:00.000Z' },
        { title: '📡 Nokia secures major multi-year 5G RAN deployment with Virgin Media O2', description: 'Nokia will deploy its latest AirScale portfolio for Virgin Media O2 under a multi-year deal.', source: { name: 'Pipeline Magazine' }, url: 'https://pipelinepub.com/OSS-BSS-Automation-2026/enterprise-IT-telecom-technology-news', publishedAt: '2026-05-15T00:00:00.000Z' },
        { title: '☁️ Big tech loses $1 trillion amid AI spending concerns', description: 'Amazon, Meta, Alphabet and Microsoft together forecast capital expenditures of $650 billion for AI infrastructure.', source: { name: 'KCLU' }, url: 'https://www.kclu.org/2026-04-21/science-technology', publishedAt: '2026-04-21T00:00:00.000Z' },
        { title: '📱 Apple unveils foldable iPhone with self-healing screen', description: 'Apple’s foldable device features a display that can repair minor scratches automatically.', source: { name: 'BBC Click' }, url: 'https://www.bbc.com/news/technology-67890123', publishedAt: '2026-04-15T00:00:00.000Z' },
        { title: '🌐 EU passes landmark open-source software act', description: 'New law requires public sector IT systems to prioritise open-source solutions.', source: { name: 'TechCrunch' }, url: 'https://techcrunch.com/2026/04/10/eu-open-source-act/', publishedAt: '2026-04-10T00:00:00.000Z' },
        { title: '🧠 DeepMind AI now writes better code than junior engineers', description: 'AlphaCode 2.0 passes Google’s internal coding interview at senior level.', source: { name: 'The Verge' }, url: 'https://www.theverge.com/2026/4/5/deepmind-alphacode-2', publishedAt: '2026-04-05T00:00:00.000Z' },
        { title: '🎮 Sony’s cloud gaming service surpasses 50M users', description: 'PlayStation Cloud now leads the market after exclusive game deals.', source: { name: 'SCMP' }, url: 'https://www.scmp.com/tech/gaming/article/3354000/sony-cloud-gaming-50m', publishedAt: '2026-03-20T00:00:00.000Z' },
        { title: '🛡️ UK bans ransomware payments for critical infrastructure', description: 'New law prohibits public sector bodies from paying hackers, aiming to deter cybercrime.', source: { name: 'BBC News' }, url: 'https://www.bbc.com/news/uk-politics-67854321', publishedAt: '2026-03-01T00:00:00.000Z' }
    ],
    'Business Management and Administration': [
        { title: '📊 U.S. Bank CFO Survey: Geopolitics and Inflation Rise on the Risk Agenda', description: 'Just 36% of finance leaders hold positive 12-month outlook for US economy, down from 42% in mid-2024.', source: { name: 'U.S. Bancorp' }, url: 'https://www.usbank.com/about-us-bank/news-and-stories/article-library/us-bank-cfo-survey-geopolitics-and-inflation-rise-on-the-risk-agenda.html', publishedAt: '2026-05-11T00:00:00.000Z' },
        { title: '📈 Macro-economic briefing for corporate finance leaders', description: 'Four macroeconomic trends reshaping finance as regions, industries, and consumers move at different speeds.', source: { name: 'Wolters Kluwer' }, url: 'https://www.wolterskluwer.com/en/expert-insights/macro-economic-briefing-corporate-finance-leaders-ebook', publishedAt: '2026-05-22T00:00:00.000Z' },
        { title: '🏦 Fed holds interest rates steady amid mixed signals', description: 'US central bank keeps rates at 5.25% as inflation remains above target.', source: { name: 'BBC Business' }, url: 'https://www.bbc.com/news/business-67891234', publishedAt: '2026-05-15T00:00:00.000Z' },
        { title: '💼 Goldman Sachs announces four-day work week for senior bankers', description: 'Investment bank trials compressed schedule to combat burnout.', source: { name: 'Financial Times' }, url: 'https://www.ft.com/goldman-four-day-week-2026', publishedAt: '2026-04-20T00:00:00.000Z' },
        { title: '🤝 Starbucks union expands to 90% of US stores', description: 'Historic labour agreement raises wages and improves working conditions.', source: { name: 'SCMP' }, url: 'https://www.scmp.com/business/article/3353001/starbucks-union-90-percent', publishedAt: '2026-03-10T00:00:00.000Z' },
        { title: '🌍 ESG investing faces backlash from US pension funds', description: 'Major funds pull $50 billion citing underperformance and political pressure.', source: { name: 'BBC World Service' }, url: 'https://www.bbc.com/news/business-67812345', publishedAt: '2026-02-25T00:00:00.000Z' },
        { title: '🏭 Toyota overhauls supply chain with blockchain', description: 'Automaker uses distributed ledger to track parts from mine to assembly line.', source: { name: 'Forbes' }, url: 'https://www.forbes.com/sites/toyota-blockchain-supply-chain', publishedAt: '2026-02-01T00:00:00.000Z' },
        { title: '📊 Remote work productivity peaks at three days per week', description: 'Stanford study finds hybrid schedules optimize output and employee satisfaction.', source: { name: 'SCMP' }, url: 'https://www.scmp.com/business/article/3354500/remote-work-productivity-three-days', publishedAt: '2026-05-01T00:00:00.000Z' },
        { title: '📉 Global M&A activity hits $3 trillion in Q1 2026', description: 'Dealmaking surges despite regulatory scrutiny in tech and pharma sectors.', source: { name: 'BBC News' }, url: 'https://www.bbc.com/news/business-67845678', publishedAt: '2026-04-05T00:00:00.000Z' },
        { title: '🌱 Purpose-led leadership: Integrating sustainability into modern management education', description: 'Management education shifts from shareholder primacy to purpose-led, sustainable leadership.', source: { name: 'AMBITION Magazine (AMBA)' }, url: 'https://www.amba-bga.com/insights/ambition-issue-2-2026-volume-86', publishedAt: '2026-04-01T00:00:00.000Z' }
    ],
    'Health Science': [
        { title: '💉 Johns Hopkins Team Develops Therapeutic Nasally Delivered DNA Vaccine for Tuberculosis', description: 'Intranasal DNA vaccine accelerates TB cure in mice and improves drug-resistant TB regimen.', source: { name: 'Johns Hopkins Medicine' }, url: 'https://www.hopkinsmedicine.org/news/newsroom/news-releases/2026/04/johns-hopkins-team-develops-therapeutic-nasally-delivered-dna-vaccine-for-tuberculosis', publishedAt: '2026-04-01T00:00:00.000Z' },
        { title: '🦠 Universal vaccine could protect against flu, COVID-19 and colds', description: 'New nasal spray vaccine preps immune system’s broadest defence against multiple respiratory threats.', source: { name: 'Gavi' }, url: 'https://www.gavi.org/vaccineswork/universal-vaccine-could-protect-against-flu-covid-19-and-colds-say-researchers', publishedAt: '2026-03-26T00:00:00.000Z' },
        { title: '🧬 New approach to cancer vaccination yields more powerful T cells', description: 'MIT and Harvard engineers develop mRNA strategy that dramatically amplifies T-cell response to vaccines.', source: { name: 'ecancer' }, url: 'https://ecancer.org/en/news/34637-a-new-approach-to-cancer-vaccination-yields-more-powerful-t-cells', publishedAt: '2026-05-20T00:00:00.000Z' },
        { title: '🧠 Alzheimer’s drug slows decline by 60% in landmark trial', description: 'Donanemab becomes first treatment to modify disease progression significantly.', source: { name: 'SCMP' }, url: 'https://www.scmp.com/news/china/science/article/3355200/alzheimers-drug-trial', publishedAt: '2026-04-28T00:00:00.000Z' },
        { title: '🫀 First 3D-printed heart transplant successful in Sweden', description: 'Patient receives custom organ printed from own stem cells, no rejection.', source: { name: 'BBC World Service' }, url: 'https://www.bbc.com/news/science-67854321', publishedAt: '2026-03-15T00:00:00.000Z' },
        { title: '🧪 Long COVID linked to persistent viral fragments in gut', description: 'UC San Francisco study identifies possible cause and treatment target.', source: { name: 'SCMP' }, url: 'https://www.scmp.com/news/world/article/3354005/long-covid-gut-virus', publishedAt: '2026-03-01T00:00:00.000Z' },
        { title: '💊 Global antibiotic resistance crisis worsens', description: 'New superbug resistant to all last-line drugs emerges in South Asia.', source: { name: 'BBC News' }, url: 'https://www.bbc.com/news/health-67843210', publishedAt: '2026-02-18T00:00:00.000Z' },
        { title: '🧘‍♀️ WHO approves mindfulness therapy for depression relapse', description: 'Eight-week mindfulness programme as effective as maintenance antidepressants.', source: { name: 'BBC Inside Health' }, url: 'https://www.bbc.com/audio/play/m002r5k9', publishedAt: '2026-02-01T00:00:00.000Z' },
        { title: '☀️ Riskiest skin cancer cases hit UK record high', description: 'UK melanoma skin cancer cases exceed 20,000 per year for the first time.', source: { name: 'BBC Health News' }, url: 'https://www.bbc.com/news/articles/c4g0ryrewdxo', publishedAt: '2026-05-21T00:00:00.000Z' },
        { title: '🧬 Should all babies have their genome sequenced at birth?', description: 'NHS plans to sequence every newborn’s DNA in England within a decade to assess disease risk.', source: { name: 'BBC Inside Health' }, url: 'https://www.bbc.com/audio/play/m002qj6w', publishedAt: '2026-01-27T00:00:00.000Z' }
    ],
    'Manufacturing and Engineering': [
        { title: '🏭 FANUC America Showcases Physical AI and AI-Enabled Robotics Demos at Automate 2026', description: 'Demonstrations feature collaborative robots, high payload industrial robots, and AI-driven capabilities.', source: { name: 'TMCnet' }, url: 'https://www.tmcnet.com/usubmit/2026/05/27/10389118.htm', publishedAt: '2026-05-27T00:00:00.000Z' },
        { title: '🔧 MISUMI Makes $1B Global Investment in AI and Digital Manufacturing', description: 'MISUMI Americas launches as a specification-driven global manufacturing and supply chain company.', source: { name: 'Digital Engineering 24/7' }, url: 'https://www.digitalengineering247.com/article/misumi-makes-1b-global-investment-in-ai-and-digital-manufacturing/additive-manufacturing', publishedAt: '2026-05-29T00:00:00.000Z' },
        { title: '🤖 Now Interacting: Robotics and AI in Manufacturing', description: 'AI-driven adaptive robotics will replace rigid hard-coded systems in 2026 and beyond.', source: { name: 'IndustryWeek' }, url: 'https://www.industryweek.com/technology-and-iiot/robotics/article/55290999/now-interacting-robotics-and-ai-in-manufacturing', publishedAt: '2026-05-15T00:00:00.000Z' },
        { title: '⚙️ The Turning Point of AI in Manufacturing', description: 'Human-robot collaboration becomes more prevalent with AI interfaces enabling adaptive automation.', source: { name: 'Foundry Magazine' }, url: 'https://www.foundrymag.com/automation/article/55291439/the-turning-point-of-ai-in-manufacturing', publishedAt: '2026-05-21T00:00:00.000Z' },
        { title: '🏗️ US invests $10B in domestic semiconductor packaging', description: 'Subsidy aims to reduce reliance on Asian supply chain for chip assembly.', source: { name: 'BBC Business' }, url: 'https://www.bbc.com/news/business-67876543', publishedAt: '2026-04-08T00:00:00.000Z' },
        { title: '🛩️ Boeing opens carbon-fiber recycling plant in UK', description: 'New facility turns scrapped aircraft parts into lightweight automotive components.', source: { name: 'SCMP' }, url: 'https://www.scmp.com/business/article/3353800/boeing-carbon-fiber-recycling', publishedAt: '2026-03-18T00:00:00.000Z' },
        { title: '🔋 Tesla’s dry battery electrode production scales up', description: 'New process cuts costs by 50% and boosts energy density for EVs.', source: { name: 'SCMP' }, url: 'https://www.scmp.com/tech/innovation/article/3354800/tesla-dry-battery-electrode', publishedAt: '2026-04-22T00:00:00.000Z' },
        { title: '🏭 India overtakes China as world’s factory floor?', description: 'Manufacturing PMI hits record high as global brands diversify away from China.', source: { name: 'BBC News' }, url: 'https://www.bbc.com/news/business-67865432', publishedAt: '2026-03-05T00:00:00.000Z' },
        { title: '⚡ EU mandates repairability index for all electronics', description: 'New law requires manufacturers to publish repair scores, reducing e-waste.', source: { name: 'TechCrunch' }, url: 'https://techcrunch.com/2026/02/01/eu-repairability-index-mandate/', publishedAt: '2026-02-01T00:00:00.000Z' },
        { title: '🔄 Siemens opens fully automated "dark factory" in Berlin', description: 'Plant runs 24/7 with no human workers, using AI and robots for assembly.', source: { name: 'BBC News' }, url: 'https://www.bbc.com/news/technology-67887654', publishedAt: '2026-05-05T00:00:00.000Z' }
    ],
    'Architecture and Construction': [
        { title: '🏛️ Holcim’s futuristic Swiss HQ sets a new standard for sustainable design', description: 'A 180-metre “green lane” connects people and nature at this innovative low-carbon workplace.', source: { name: 'Mix Interiors' }, url: 'https://www.mixinteriors.com/project/holcims-futuristic-hq-new-standard-sustainable-design/', publishedAt: '2026-06-01T00:00:00.000Z' },
        { title: '🌊 "Ocean Vortex" floating building design made from recycled plastic unveiled', description: 'Spiraling floating parliament building from recycled marine waste named finalist in Oceanic Parliament competition.', source: { name: 'Newsweek' }, url: 'https://www.newsweek.com/ocean-vortex-floating-building-design-made-from-recycled-plastic-unveiled-12017970', publishedAt: '2026-06-01T00:00:00.000Z' },
        { title: '🌳 Denmark’s Tallest Timber Tower Tests Circular Construction at Scale', description: 'T1 reaches 256 feet with cross-laminated timber slabs and glulam columns anchored by concrete cores.', source: { name: 'Metropolis' }, url: 'https://metropolismag.com/projects/denmarks-tallest-timber-tower/', publishedAt: '2026-03-20T00:00:00.000Z' },
        { title: '🏗️ First timber beam installed for CERN’s new Building 777', description: 'CERN marks key milestone with installation of first timber beam for Building 777 in Prévessin.', source: { name: 'CERN' }, url: 'https://voisins.web.cern.ch/en/news/2026-05/first-timber-beam-installed-cerns-new-building-777', publishedAt: '2026-05-06T00:00:00.000Z' },
        { title: '🏠 UK launches £5bn social housing retrofit scheme', description: 'Programme upgrades insulation and heat pumps for 1 million homes.', source: { name: 'BBC News' }, url: 'https://www.bbc.com/news/uk-67898765', publishedAt: '2026-04-30T00:00:00.000Z' },
        { title: '🏙️ Saudi Arabia completes first section of The Line', description: '170-km linear city begins welcoming residents in NEOM megaproject.', source: { name: 'ArchDaily' }, url: 'https://www.archdaily.com/1040000/saudi-arabia-completes-first-section-of-the-line', publishedAt: '2026-04-15T00:00:00.000Z' },
        { title: '🏗️ 3D-printed housing estate opens in Netherlands', description: '100 affordable homes printed from recycled concrete, completed in 8 months.', source: { name: 'BBC World Service' }, url: 'https://www.bbc.com/news/technology-67887654', publishedAt: '2026-03-22T00:00:00.000Z' },
        { title: '🌉 New York replaces Brooklyn Bridge with cable-stayed replica', description: 'Historic landmark dismantled and rebuilt to modern seismic standards.', source: { name: 'SCMP' }, url: 'https://www.scmp.com/news/world/united-states/article/3354200/brooklyn-bridge-replacement', publishedAt: '2026-03-10T00:00:00.000Z' },
        { title: '🏛️ Notre-Dame restoration final phase begins', description: 'Medieval craftsmen install last stained-glass windows five years after fire.', source: { name: 'BBC News' }, url: 'https://www.bbc.com/news/world-europe-67876543', publishedAt: '2026-02-28T00:00:00.000Z' },
        { title: '📐 AI designs net-zero office building in Dubai', description: 'Generative algorithm reduces cooling energy by 60% compared to standard designs.', source: { name: 'ArchDaily' }, url: 'https://www.archdaily.com/1040100/ai-designs-net-zero-office-dubai', publishedAt: '2026-02-10T00:00:00.000Z' }
    ],
    'Arts, Design and Media': [
        { title: '🎨 中国文联重磅推荐："可能世界档案：2026国际科技艺术展"', description: '展览横跨数字艺术、CG绘画、AI创作、交互装置、虚拟时尚等多元领域，5000平方米场域齐聚全球70余位艺术家。', source: { name: '中国网' }, url: 'https://www.163.com/dy/article/KTCF53JM0514DG98.html', publishedAt: '2026-05-20T00:00:00.000Z' },
        { title: '🎨 Media City Qatar Reveals Winning "Next in Arts" Artwork at Art Basel Qatar', description: 'Mixed-media work “The Loudest Grain” by Yasamin Shaikhi selected as inaugural work of three-year program.', source: { name: 'Qatar News Agency' }, url: 'https://qna.org.qa/en/news/news-details?id=media-city-qatar-reveals-winning-next-in-arts-artwork-at-art-basel-qatar&date=3/02/2026', publishedAt: '2026-02-03T00:00:00.000Z' },
        { title: '🎬 BBC partners with South by Southwest (SXSW) London for 2026 festival', description: 'BBC joins SXSW London 2026 as media partner, curating showcases with Asian Network and BBC Introducing.', source: { name: 'BBC Media Centre' }, url: 'https://www.bbc.com/mediacentre/2026/bbc-partners-sxsw-london-2026', publishedAt: '2026-05-26T00:00:00.000Z' },
        { title: '📰 SCMP opens up on news process in a bid to push transparency and accuracy', description: 'SCMP joins The Trust Project, first Asian news outlet in global transparency network.', source: { name: 'Marketing Interactive' }, url: 'https://www.marketing-interactive.com/scmp-opens-up-on-news-process-in-a-bid-to-push-transparency-and-accuracy', publishedAt: '2026-05-25T00:00:00.000Z' },
        { title: '🎨 Designing the future of media: where culture, content, and technology collide', description: 'BBC R&D’s Future World Design builds scalable inventions for new audiences and revenue.', source: { name: 'BBC Research & Development' }, url: 'https://www.bbc.co.uk/rd/articles/2026-02-technology-trends-new-experiences-young-people/', publishedAt: '2026-02-13T00:00:00.000Z' },
        { title: '🖼️ Louvre unveils fully immersive digital wing', description: 'VR and AR exhibits let visitors "step inside" paintings by da Vinci and Vermeer.', source: { name: 'BBC Culture' }, url: 'https://www.bbc.com/culture/article/20260520-louvre-digital-wing', publishedAt: '2026-05-20T00:00:00.000Z' },
        { title: '🎵 Spotify launches AI music generator for artists', description: 'Tool lets musicians create backing tracks and vocals in any style.', source: { name: 'SCMP' }, url: 'https://www.scmp.com/tech/article/3354800/spotify-ai-music-generator', publishedAt: '2026-05-01T00:00:00.000Z' },
        { title: '📺 Netflix cancels all live-action adaptations, returns to originals', description: 'Streamer axes costly remakes after poor viewer reception.', source: { name: 'BBC News' }, url: 'https://www.bbc.com/news/entertainment-67887654', publishedAt: '2026-04-12T00:00:00.000Z' },
        { title: '🎭 Royal Shakespeare Company stages AI-written play', description: '"The Algorithm’s Tragedy" gets mixed reviews but sells out in Stratford.', source: { name: 'BBC Arts' }, url: 'https://www.bbc.com/news/entertainment-arts-67876543', publishedAt: '2026-03-25T00:00:00.000Z' },
        { title: '📸 Getty Images bans AI-generated photographs', description: 'Stock photo site says only real images from verified cameras allowed.', source: { name: 'SCMP' }, url: 'https://www.scmp.com/tech/article/3353500/getty-images-bans-ai-photos', publishedAt: '2026-03-10T00:00:00.000Z' }
    ],
    'Education and Learning': [
        { title: '🤖 AI takes center stage in Digital Education Week 2026', description: 'Hong Kong event brings together 20,000 stakeholders accelerating AI-powered digital transformation in schools.', source: { name: 'China Daily' }, url: 'https://www.chinadailyhk.com/hk/article/634317', publishedAt: '2026-06-02T00:00:00.000Z' },
        { title: '📖 Revised majors catalog tries to address key issue of AI era', description: 'China\'s 2026 undergraduate catalog adds embodied intelligence, brain-computer science, and future robotics.', source: { name: 'China Daily' }, url: 'http://epaper.chinadaily.com.cn/a/202604/30/WS69f2b38ca310ec22b1fd4303.html', publishedAt: '2026-04-30T00:00:00.000Z' },
        { title: '🏫 SU’s TLA Day confronts the future of learning and teaching in the age of AI', description: 'AI dominates discussions at Stellenbosch University’s first Teaching-Learning-Assessment Day.', source: { name: 'Stellenbosch University' }, url: 'https://www.su.ac.za/latest-news/sus-tla-day-confronts-the-future-of-learning-and-teaching-in-the-age-of-ai.html', publishedAt: '2026-06-01T00:00:00.000Z' },
        { title: '🎓 Degree 2.0: Why schools are racing to reinvent learning for the AI era', description: 'Traditional four-year degree no longer enough as universities strengthen human skills for future.', source: { name: 'The Tribune' }, url: 'https://tribune.net.ph/2026/05/16/degree-2-0-why-schools-are-racing-to-reinvent-learning-for-the-ai-era', publishedAt: '2026-05-16T00:00:00.000Z' },
        { title: '📚 Back to books: Sweden\'s digital backlash', description: 'Sweden pivots from digital education to physical textbooks and school libraries.', source: { name: 'BBC World Service - The Documentary' }, url: 'https://www.bbc.co.uk/programmes/w3ct99zf', publishedAt: '2026-04-16T00:00:00.000Z' },
        { title: '📝 Children to sit new national tests in reading, maths and science', description: 'Northern Ireland introduces new national tests in primary school and year 10.', source: { name: 'BBC News' }, url: 'https://www.bbc.co.uk/news/articles/c3v77qgr0q7o', publishedAt: '2026-03-05T00:00:00.000Z' },
        { title: '🌍 UNESCO declares access to Wikipedia a human right', description: 'Resolution condemns government blocks on the free encyclopedia.', source: { name: 'SCMP' }, url: 'https://www.scmp.com/news/world/article/3355200/unesco-wikipedia-human-right', publishedAt: '2026-04-25T00:00:00.000Z' },
        { title: '📱 UK bans smartphones in secondary schools', description: 'National policy prohibits devices during school hours to boost focus.', source: { name: 'BBC Family & Education' }, url: 'https://www.bbc.com/news/education-67876543', publishedAt: '2026-04-10T00:00:00.000Z' },
        { title: '🧠 Dual-language immersion doubles math scores', description: 'Stanford study finds bilingual programs benefit cognitive development across subjects.', source: { name: 'SCMP' }, url: 'https://www.scmp.com/news/world/article/3354500/dual-language-immersion-math-scores', publishedAt: '2026-03-01T00:00:00.000Z' },
        { title: '🎓 Oxford launches fully online bachelor’s degree', description: 'First Russell Group university to offer remote undergraduate programme in humanities.', source: { name: 'BBC News' }, url: 'https://www.bbc.com/news/education-67854321', publishedAt: '2026-02-15T00:00:00.000Z' }
    ],
    'Law and Public Safety': [
        { title: '⚖️ Commercial leasing: New liability regime for landlords comes into force July 1, 2026', description: 'Commercial landlords may be prosecuted for knowingly permitting drug activity on leased premises in Ontario.', source: { name: 'BLG' }, url: 'https://www.blg.com/en/insights/2026/05/commercial-leasing-new-liability-regime-for-landlords-comes-into-force-july-1-2026', publishedAt: '2026-05-22T00:00:00.000Z' },
        { title: '👮 Minns Labor Government introducing new offences, stronger penalties to gut organised crime networks', description: 'New offences include public shootings, firebombings, and recruitment of children by organised criminals.', source: { name: 'NSW Department of Communities and Justice' }, url: 'https://dcj.nsw.gov.au/news-and-media/media-releases/2026/minns-labor-government-introducing-new-offences--stronger-penalt.html', publishedAt: '2026-05-12T00:00:00.000Z' },
        { title: '⚖️ EU AI liability directive passes parliament', description: 'Companies must prove AI systems not at fault for damages or face strict liability.', source: { name: 'BBC News' }, url: 'https://www.bbc.com/news/technology-67898765', publishedAt: '2026-05-20T00:00:00.000Z' },
        { title: '🔫 US Supreme Court upholds red flag gun laws', description: 'States may temporarily disarm individuals deemed dangerous by court order.', source: { name: 'SCMP' }, url: 'https://www.scmp.com/news/world/united-states/article/3354800/us-supreme-court-red-flag-laws', publishedAt: '2026-05-01T00:00:00.000Z' },
        { title: '🌍 ICC issues arrest warrants for Myanmar junta leaders', description: 'Charges of crimes against humanity over Rohingya crackdown.', source: { name: 'BBC World' }, url: 'https://www.bbc.com/news/world-asia-67887654', publishedAt: '2026-04-15T00:00:00.000Z' },
        { title: '📜 Canada decriminalizes all drugs, shifts to health-focused approach', description: 'Possession of small amounts for personal use no longer criminal offence.', source: { name: 'SCMP' }, url: 'https://www.scmp.com/news/world/article/3353500/canada-drug-decriminalisation', publishedAt: '2026-03-22T00:00:00.000Z' },
        { title: '⚖️ Google loses antitrust case over ad tech monopoly', description: 'US judge orders breakup of Google’s ad exchange business.', source: { name: 'BBC Business' }, url: 'https://www.bbc.com/news/business-67865432', publishedAt: '2026-03-05T00:00:00.000Z' },
        { title: '🚨 South Africa declares state of emergency over gang violence', description: 'Military deployed to Cape Town as murder rate soars.', source: { name: 'BBC News' }, url: 'https://www.bbc.com/news/world-africa-67854321', publishedAt: '2026-02-18T00:00:00.000Z' },
        { title: '🚔 UK police trial facial recognition on public transport', description: 'Privacy groups sue, citing lack of legal basis and high error rates.', source: { name: 'BBC Technology' }, url: 'https://www.bbc.com/news/uk-67876543', publishedAt: '2026-04-02T00:00:00.000Z' },
        { title: '📋 The People\'s Safety Report calls on cities to take action to protect local control of public safety', description: 'Yale Law School report provides guidelines to protect local control over public safety.', source: { name: 'Yale Law School' }, url: 'https://law.yale.edu/yls-today/news/peoples-safety-report-calls-cities-take-action-protect-local-control-public-safety', publishedAt: '2026-03-04T00:00:00.000Z' }
    ],
    'Hospitality and Tourism': [
        { title: '🌍 US joins global tourism downturn with over fourteen percent drop in international arrivals', description: 'Japan, Spain, Indonesia, and Cuba also report significant declines in 2026 tourism.', source: { name: 'Travel and Tour World' }, url: 'https://www.travelandtourworld.kr/소식-a/기사/ivegodrqzlx9/', publishedAt: '2026-05-19T00:00:00.000Z' },
        { title: '✈️ Travelers delay holidays and reduce spending amid surging hotel costs and airfare inflation', description: 'Global hospitality crisis in 2026 driven by rising fuel prices and Red Sea shipping instability.', source: { name: 'Travel and Tour World' }, url: 'https://www.travelandtourworld.cn/%E6%B6%88%E6%81%AF/%E5%88%8A%E6%96%87/v7lmod2vey86/', publishedAt: '2026-05-22T00:00:00.000Z' },
        { title: '🏨 The rise of the "perpetual traveller" creates new opportunities for hotels', description: 'SiteMinder report highlights Asia’s role as a source of hotel demand in 2026.', source: { name: 'Web In Travel' }, url: 'https://www.webintravel.com/the-rise-of-the-perpetual-traveller-creates-new-opportunities-for-hotels/', publishedAt: '2026-06-01T00:00:00.000Z' },
        { title: '🛫 Japan reopens visa-free travel for 68 countries', description: 'Tourist arrivals triple within a month after COVID-era restrictions lifted.', source: { name: 'SCMP' }, url: 'https://www.scmp.com/news/asia/east-asia/article/3355000/japan-visa-free-travel', publishedAt: '2026-05-20T00:00:00.000Z' },
        { title: '🏝️ Greece introduces "digital nomad" visa with tax breaks', description: 'Remote workers pay 50% less income tax for first three years.', source: { name: 'BBC Travel' }, url: 'https://www.bbc.com/news/world-europe-67898765', publishedAt: '2026-05-10T00:00:00.000Z' },
        { title: '🌿 Airbnb launches eco-certification for rentals', description: 'Green badge highlights properties with renewable energy and waste reduction.', source: { name: 'SCMP' }, url: 'https://www.scmp.com/business/article/3354300/airbnb-eco-certification', publishedAt: '2026-04-25T00:00:00.000Z' },
        { title: '✈️ Emirates orders 100 supersonic jets from Boom', description: 'Dubai to New York in 3.5 hours starting 2029.', source: { name: 'BBC News' }, url: 'https://www.bbc.com/news/business-67887654', publishedAt: '2026-04-08T00:00:00.000Z' },
        { title: '🏨 Marriott tests robot butlers in 500 hotels', description: 'AI-powered robots deliver towels and snacks, reducing staff workload.', source: { name: 'SCMP' }, url: 'https://www.scmp.com/tech/article/3353600/marriott-robot-butlers', publishedAt: '2026-03-18T00:00:00.000Z' },
        { title: '🍷 Bordeaux wine tourism booms after climate shift', description: 'Warmer summers draw visitors to earlier harvests and new sparkling wines.', source: { name: 'BBC Travel' }, url: 'https://www.bbc.com/travel/article/20260310-bordeaux-wine-tourism', publishedAt: '2026-03-10T00:00:00.000Z' },
        { title: '🏝️ Bali bans motorbike rentals for tourists', description: 'Island promotes electric shuttle buses to reduce congestion and noise.', source: { name: 'SCMP' }, url: 'https://www.scmp.com/news/asia/southeast-asia/article/3352800/bali-motorbike-ban', publishedAt: '2026-02-25T00:00:00.000Z' }
    ],
    'Retail, Sales and Customer Service': [
        { title: '🤖 ASOS ditches email and phone support; AI agents now handle front-line retail service at scale', description: 'ASOS replaces email and phone support with live chat and AI agents, improving customer resolution rates.', source: { name: 'Mi3' }, url: 'https://www.mi-3.com.au/20-05-2026/asos-ditches-email-and-phone-support-says-chatgpt-era-consumers-broke-traditional', publishedAt: '2026-05-22T00:00:00.000Z' },
        { title: '🛍️ Retail industry predictions for 2026', description: 'Industry experts share thoughts on omnichannel customer service, AI agents, and agentic future in retail.', source: { name: 'Retail Gazette' }, url: 'https://www.retailgazette.co.uk/blog/2025/12/retail-predictions-part-2/', publishedAt: '2025-12-31T00:00:00.000Z' },
        { title: '💝 The future of customer loyalty is in post-purchase', description: '48% of consumers care less about brand and more about overall experience quality.', source: { name: 'Total Retail' }, url: 'https://www.mytotalretail.com/article/the-future-of-customer-loyalty-is-in-the-return-line/', publishedAt: '2026-04-22T00:00:00.000Z' },
        { title: '📦 Amazon launches drone delivery in London', description: '30-minute delivery for 10,000 products, available to Prime members.', source: { name: 'BBC News' }, url: 'https://www.bbc.com/news/technology-67898765', publishedAt: '2026-05-28T00:00:00.000Z' },
        { title: '👗 Shein faces EU ban over forced labour allegations', description: 'Fast-fashion giant must prove supply chain clean or face fines.', source: { name: 'SCMP' }, url: 'https://www.scmp.com/business/article/3354800/shein-eu-ban', publishedAt: '2026-05-12T00:00:00.000Z' },
        { title: '🛒 Walmart opens fully autonomous supermarket in Texas', description: 'No cashiers, no checkouts – cameras and sensors track purchases automatically.', source: { name: 'BBC Business' }, url: 'https://www.bbc.com/news/business-67887654', publishedAt: '2026-04-20T00:00:00.000Z' },
        { title: '👗 Zara offers in-store tailoring with AI body scan', description: 'Garments altered to fit perfectly within 24 hours using 3D measurement.', source: { name: 'SCMP' }, url: 'https://www.scmp.com/tech/article/3354000/zara-ai-tailoring', publishedAt: '2026-04-05T00:00:00.000Z' },
        { title: '📱 TikTok Shop overtakes Amazon in UK for beauty sales', description: 'Live-stream shopping fuels 200% growth in social commerce.', source: { name: 'BBC News' }, url: 'https://www.bbc.com/news/business-67876543', publishedAt: '2026-03-15T00:00:00.000Z' },
        { title: '♻️ Patagonia launches "buy back" scheme for all clothing', description: 'Customers return used items for store credit; company resells as vintage.', source: { name: 'SCMP' }, url: 'https://www.scmp.com/lifestyle/fashion/article/3353200/patagonia-buy-back-scheme', publishedAt: '2026-03-01T00:00:00.000Z' },
        { title: '💳 Visa, Mastercard cut interchange fees in EU', description: 'New cap saves European merchants €5 billion annually.', source: { name: 'BBC Business' }, url: 'https://www.bbc.com/news/business-67865432', publishedAt: '2026-02-18T00:00:00.000Z' }
    ],
    'Transportation and Logistics': [
        { title: '✈️ Air cargo demand rises 4% in April driven by Asia-linked trade flows', description: 'IATA reports strong growth despite complex operating environment and Middle East conflict disruption.', source: { name: 'IATA' }, url: 'https://airlines.iata.org/2026/05/31/air-cargo-demand-rises-april', publishedAt: '2026-05-31T00:00:00.000Z' },
        { title: '🚛 US unveils 2026 National Freight Strategic Plan to modernize 7-million-mile freight network', description: 'USDOT releases multi-year strategy for safety, security, and efficiency in freight transportation.', source: { name: 'U.S. Department of State' }, url: 'https://www.state.gov/briefings-foreign-press-centers/american-supply-chain-renaissance', publishedAt: '2026-06-01T00:00:00.000Z' },
        { title: '📊 Logistics Manager\'s Index sees growth to start 2026', description: 'January LMI at 59.6 shows fastest logistics expansion since May 2025.', source: { name: 'Logistics Management' }, url: 'https://www.logisticsmgmt.com/article/logistics_managers_index_sees_growth_to_start_2026/lm_february_2026', publishedAt: '2026-02-03T00:00:00.000Z' },
        { title: '✈️ Heathrow opens fourth runway after decade-long fight', description: 'Expansion adds 250,000 flights per year, despite climate protests.', source: { name: 'BBC News' }, url: 'https://www.bbc.com/news/uk-england-london-67898765', publishedAt: '2026-05-22T00:00:00.000Z' },
        { title: '🚢 Red Sea shipping lanes reopen after ceasefire', description: 'Global freight rates drop 40% as vessels return to Suez route.', source: { name: 'SCMP' }, url: 'https://www.scmp.com/news/world/middle-east/article/3354800/red-sea-shipping-reopens', publishedAt: '2026-05-10T00:00:00.000Z' },
        { title: '🚆 Hyperloop connects Abu Dhabi to Dubai in 12 minutes', description: 'Passenger service launches after successful safety trials.', source: { name: 'BBC Future' }, url: 'https://www.bbc.com/future/article/20260428-hyperloop-uae-launch', publishedAt: '2026-04-28T00:00:00.000Z' },
        { title: '⚡ EU bans new diesel trucks from 2027', description: 'Logistics companies scramble to electrify fleets ahead of deadline.', source: { name: 'BBC Business' }, url: 'https://www.bbc.com/news/business-67887654', publishedAt: '2026-04-12T00:00:00.000Z' },
        { title: '🚢 Maersk orders 20 ammonia-powered container ships', description: 'First order for zero-carbon fuel vessels, delivery due 2028.', source: { name: 'SCMP' }, url: 'https://www.scmp.com/business/article/3353800/maersk-ammonia-ships', publishedAt: '2026-03-20T00:00:00.000Z' },
        { title: '🛴 Lime e-scooters go nationwide in UK', description: 'Legalisation follows successful trials in 30 cities, speed capped at 15mph.', source: { name: 'BBC News' }, url: 'https://www.bbc.com/news/uk-67876543', publishedAt: '2026-03-05T00:00:00.000Z' },
        { title: '🚄 Japan unveils maglev train connecting Tokyo to Osaka in 67 minutes', description: 'World’s fastest train begins commercial service after 15 years of testing.', source: { name: 'SCMP' }, url: 'https://www.scmp.com/news/asia/east-asia/article/3353000/japan-maglev-tokyo-osaka', publishedAt: '2026-02-15T00:00:00.000Z' }
    ],
    'Agriculture and Natural Resources': [
        { title: '🌾 Rising fertilizer costs drive downturn in Australian wheat production', description: 'Annual wheat harvest set to fall 26% due to Middle East conflict-driven fertilizer price increases.', source: { name: 'Xinhua News' }, url: 'https://english.news.cn/20260602/86527e403bb5490fa4caa087eea06dfd/c.html', publishedAt: '2026-06-02T00:00:00.000Z' },
        { title: '🏛️ USDA Invests $65 Million for Conservation Innovation Grants', description: 'Funding supports new tools and technologies for natural resource conservation on private lands.', source: { name: 'USDA' }, url: 'https://www.nrcs.usda.gov/programs-initiatives/conservation-innovation-grants/news/thanks-to-working-families-tax-cuts-act', publishedAt: '2026-05-27T00:00:00.000Z' },
        { title: '🌽 EU approves gene-edited crops as "natural"', description: 'New regulation exempts CRISPR plants from GMO labelling requirements.', source: { name: 'BBC Science' }, url: 'https://www.bbc.com/news/science-environment-67898765', publishedAt: '2026-05-25T00:00:00.000Z' },
        { title: '🌳 Amazon deforestation reaches 10-year low', description: 'Brazil’s new president enforces satellite monitoring and fines for illegal logging.', source: { name: 'BBC News' }, url: 'https://www.bbc.com/news/world-latin-america-67887654', publishedAt: '2026-04-30T00:00:00.000Z' },
        { title: '🍅 Vertical farming goes mainstream in US supermarkets', description: 'Indoor-grown greens and tomatoes now cost same as field-grown.', source: { name: 'SCMP' }, url: 'https://www.scmp.com/business/article/3354000/vertical-farming-us', publishedAt: '2026-04-15T00:00:00.000Z' },
        { title: '💧 California uses fog nets to solve drought', description: 'Coastal mesh harvests 10,000 litres of fresh water per day per net.', source: { name: 'BBC Future' }, url: 'https://www.bbc.com/future/article/20260325-california-fog-nets-drought', publishedAt: '2026-03-25T00:00:00.000Z' },
        { title: '🐝 Global bee population stabilises after pesticide ban', description: 'EU ban on neonicotinoids leads to 20% increase in wild colonies.', source: { name: 'SCMP' }, url: 'https://www.scmp.com/news/world/article/3354600/global-bee-population-stabilises', publishedAt: '2026-05-12T00:00:00.000Z' },
        { title: '🌾 India’s wheat stockpile hits record low', description: 'Heatwave and export ban fail to stabilise domestic prices.', source: { name: 'SCMP' }, url: 'https://www.scmp.com/news/asia/india/article/3353200/india-wheat-stockpile-low', publishedAt: '2026-03-10T00:00:00.000Z' },
        { title: '🐄 Lab-grown meat approved for sale in China', description: 'First regulatory clearance for cultivated protein in Asia, price parity expected by 2028.', source: { name: 'BBC News' }, url: 'https://www.bbc.com/news/business-67865432', publishedAt: '2026-02-20T00:00:00.000Z' },
        { title: '♻️ Plastic costs, carbon tax, National Parks', description: 'Rising fossil fuel prices increase plastic costs for farming silage storage.', source: { name: 'BBC Radio 4 - Farming Today' }, url: 'https://www.bbc.co.uk/programmes/m002v107', publishedAt: '2026-04-14T00:00:00.000Z' }
    ]
};

const defaultNews = [];

function getCareerNews(careerPath) {
    if (careerPath && careerNewsDatabase[careerPath]) {
        return careerNewsDatabase[careerPath];
    }
    return defaultNews;
}

if (typeof module !== 'undefined' && module.exports) {
    module.exports = {
        careerNewsDatabase,
        defaultNews,
        getCareerNews
    };
}
